// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tick_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tick_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tick_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tick_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tick_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tick_5fdata_2eproto;
class TickDataMes;
struct TickDataMesDefaultTypeInternal;
extern TickDataMesDefaultTypeInternal _TickDataMes_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::TickDataMes* Arena::CreateMaybeMessage<::TickDataMes>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class TickDataMes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TickDataMes) */ {
 public:
  inline TickDataMes() : TickDataMes(nullptr) {}
  ~TickDataMes() override;
  explicit PROTOBUF_CONSTEXPR TickDataMes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TickDataMes(const TickDataMes& from);
  TickDataMes(TickDataMes&& from) noexcept
    : TickDataMes() {
    *this = ::std::move(from);
  }

  inline TickDataMes& operator=(const TickDataMes& from) {
    CopyFrom(from);
    return *this;
  }
  inline TickDataMes& operator=(TickDataMes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TickDataMes& default_instance() {
    return *internal_default_instance();
  }
  static inline const TickDataMes* internal_default_instance() {
    return reinterpret_cast<const TickDataMes*>(
               &_TickDataMes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TickDataMes& a, TickDataMes& b) {
    a.Swap(&b);
  }
  inline void Swap(TickDataMes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TickDataMes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TickDataMes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TickDataMes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TickDataMes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TickDataMes& from) {
    TickDataMes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TickDataMes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TickDataMes";
  }
  protected:
  explicit TickDataMes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBidPriceFieldNumber = 2,
    kAskPriceFieldNumber = 3,
    kBidVolumeFieldNumber = 8,
    kAskVolumeFieldNumber = 9,
    kInstrumentIDFieldNumber = 11,
    kExchangeIDFieldNumber = 12,
    kUpdateTimeFieldNumber = 13,
    kActionDayFieldNumber = 14,
    kTradingDayFieldNumber = 15,
    kLastPriceFieldNumber = 1,
    kLimitUpFieldNumber = 4,
    kLimitDownFieldNumber = 5,
    kVolumeFieldNumber = 6,
    kUpdatemillFieldNumber = 7,
    kLocalReceiveTimeFieldNumber = 10,
  };
  // repeated double bid_price = 2;
  int bid_price_size() const;
  private:
  int _internal_bid_price_size() const;
  public:
  void clear_bid_price();
  private:
  double _internal_bid_price(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_bid_price() const;
  void _internal_add_bid_price(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_bid_price();
  public:
  double bid_price(int index) const;
  void set_bid_price(int index, double value);
  void add_bid_price(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      bid_price() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_bid_price();

  // repeated double ask_price = 3;
  int ask_price_size() const;
  private:
  int _internal_ask_price_size() const;
  public:
  void clear_ask_price();
  private:
  double _internal_ask_price(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_ask_price() const;
  void _internal_add_ask_price(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_ask_price();
  public:
  double ask_price(int index) const;
  void set_ask_price(int index, double value);
  void add_ask_price(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      ask_price() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_ask_price();

  // repeated int32 bid_volume = 8;
  int bid_volume_size() const;
  private:
  int _internal_bid_volume_size() const;
  public:
  void clear_bid_volume();
  private:
  int32_t _internal_bid_volume(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_bid_volume() const;
  void _internal_add_bid_volume(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_bid_volume();
  public:
  int32_t bid_volume(int index) const;
  void set_bid_volume(int index, int32_t value);
  void add_bid_volume(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      bid_volume() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_bid_volume();

  // repeated int32 ask_volume = 9;
  int ask_volume_size() const;
  private:
  int _internal_ask_volume_size() const;
  public:
  void clear_ask_volume();
  private:
  int32_t _internal_ask_volume(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_ask_volume() const;
  void _internal_add_ask_volume(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_ask_volume();
  public:
  int32_t ask_volume(int index) const;
  void set_ask_volume(int index, int32_t value);
  void add_ask_volume(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      ask_volume() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_ask_volume();

  // string InstrumentID = 11;
  void clear_instrumentid();
  const std::string& instrumentid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_instrumentid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_instrumentid();
  PROTOBUF_NODISCARD std::string* release_instrumentid();
  void set_allocated_instrumentid(std::string* instrumentid);
  private:
  const std::string& _internal_instrumentid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instrumentid(const std::string& value);
  std::string* _internal_mutable_instrumentid();
  public:

  // string ExchangeID = 12;
  void clear_exchangeid();
  const std::string& exchangeid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_exchangeid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_exchangeid();
  PROTOBUF_NODISCARD std::string* release_exchangeid();
  void set_allocated_exchangeid(std::string* exchangeid);
  private:
  const std::string& _internal_exchangeid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchangeid(const std::string& value);
  std::string* _internal_mutable_exchangeid();
  public:

  // string update_time = 13;
  void clear_update_time();
  const std::string& update_time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_update_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_update_time();
  PROTOBUF_NODISCARD std::string* release_update_time();
  void set_allocated_update_time(std::string* update_time);
  private:
  const std::string& _internal_update_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_update_time(const std::string& value);
  std::string* _internal_mutable_update_time();
  public:

  // string Action_Day = 14;
  void clear_action_day();
  const std::string& action_day() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_action_day(ArgT0&& arg0, ArgT... args);
  std::string* mutable_action_day();
  PROTOBUF_NODISCARD std::string* release_action_day();
  void set_allocated_action_day(std::string* action_day);
  private:
  const std::string& _internal_action_day() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action_day(const std::string& value);
  std::string* _internal_mutable_action_day();
  public:

  // string TradingDay = 15;
  void clear_tradingday();
  const std::string& tradingday() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tradingday(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tradingday();
  PROTOBUF_NODISCARD std::string* release_tradingday();
  void set_allocated_tradingday(std::string* tradingday);
  private:
  const std::string& _internal_tradingday() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tradingday(const std::string& value);
  std::string* _internal_mutable_tradingday();
  public:

  // double last_price = 1;
  void clear_last_price();
  double last_price() const;
  void set_last_price(double value);
  private:
  double _internal_last_price() const;
  void _internal_set_last_price(double value);
  public:

  // double limit_up = 4;
  void clear_limit_up();
  double limit_up() const;
  void set_limit_up(double value);
  private:
  double _internal_limit_up() const;
  void _internal_set_limit_up(double value);
  public:

  // double limit_down = 5;
  void clear_limit_down();
  double limit_down() const;
  void set_limit_down(double value);
  private:
  double _internal_limit_down() const;
  void _internal_set_limit_down(double value);
  public:

  // int32 volume = 6;
  void clear_volume();
  int32_t volume() const;
  void set_volume(int32_t value);
  private:
  int32_t _internal_volume() const;
  void _internal_set_volume(int32_t value);
  public:

  // int32 updatemill = 7;
  void clear_updatemill();
  int32_t updatemill() const;
  void set_updatemill(int32_t value);
  private:
  int32_t _internal_updatemill() const;
  void _internal_set_updatemill(int32_t value);
  public:

  // int64 local_receive_time = 10;
  void clear_local_receive_time();
  int64_t local_receive_time() const;
  void set_local_receive_time(int64_t value);
  private:
  int64_t _internal_local_receive_time() const;
  void _internal_set_local_receive_time(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:TickDataMes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > bid_price_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > ask_price_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > bid_volume_;
    mutable std::atomic<int> _bid_volume_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > ask_volume_;
    mutable std::atomic<int> _ask_volume_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr instrumentid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchangeid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr update_time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_day_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tradingday_;
    double last_price_;
    double limit_up_;
    double limit_down_;
    int32_t volume_;
    int32_t updatemill_;
    int64_t local_receive_time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tick_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TickDataMes

// double last_price = 1;
inline void TickDataMes::clear_last_price() {
  _impl_.last_price_ = 0;
}
inline double TickDataMes::_internal_last_price() const {
  return _impl_.last_price_;
}
inline double TickDataMes::last_price() const {
  // @@protoc_insertion_point(field_get:TickDataMes.last_price)
  return _internal_last_price();
}
inline void TickDataMes::_internal_set_last_price(double value) {
  
  _impl_.last_price_ = value;
}
inline void TickDataMes::set_last_price(double value) {
  _internal_set_last_price(value);
  // @@protoc_insertion_point(field_set:TickDataMes.last_price)
}

// repeated double bid_price = 2;
inline int TickDataMes::_internal_bid_price_size() const {
  return _impl_.bid_price_.size();
}
inline int TickDataMes::bid_price_size() const {
  return _internal_bid_price_size();
}
inline void TickDataMes::clear_bid_price() {
  _impl_.bid_price_.Clear();
}
inline double TickDataMes::_internal_bid_price(int index) const {
  return _impl_.bid_price_.Get(index);
}
inline double TickDataMes::bid_price(int index) const {
  // @@protoc_insertion_point(field_get:TickDataMes.bid_price)
  return _internal_bid_price(index);
}
inline void TickDataMes::set_bid_price(int index, double value) {
  _impl_.bid_price_.Set(index, value);
  // @@protoc_insertion_point(field_set:TickDataMes.bid_price)
}
inline void TickDataMes::_internal_add_bid_price(double value) {
  _impl_.bid_price_.Add(value);
}
inline void TickDataMes::add_bid_price(double value) {
  _internal_add_bid_price(value);
  // @@protoc_insertion_point(field_add:TickDataMes.bid_price)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TickDataMes::_internal_bid_price() const {
  return _impl_.bid_price_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TickDataMes::bid_price() const {
  // @@protoc_insertion_point(field_list:TickDataMes.bid_price)
  return _internal_bid_price();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TickDataMes::_internal_mutable_bid_price() {
  return &_impl_.bid_price_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TickDataMes::mutable_bid_price() {
  // @@protoc_insertion_point(field_mutable_list:TickDataMes.bid_price)
  return _internal_mutable_bid_price();
}

// repeated double ask_price = 3;
inline int TickDataMes::_internal_ask_price_size() const {
  return _impl_.ask_price_.size();
}
inline int TickDataMes::ask_price_size() const {
  return _internal_ask_price_size();
}
inline void TickDataMes::clear_ask_price() {
  _impl_.ask_price_.Clear();
}
inline double TickDataMes::_internal_ask_price(int index) const {
  return _impl_.ask_price_.Get(index);
}
inline double TickDataMes::ask_price(int index) const {
  // @@protoc_insertion_point(field_get:TickDataMes.ask_price)
  return _internal_ask_price(index);
}
inline void TickDataMes::set_ask_price(int index, double value) {
  _impl_.ask_price_.Set(index, value);
  // @@protoc_insertion_point(field_set:TickDataMes.ask_price)
}
inline void TickDataMes::_internal_add_ask_price(double value) {
  _impl_.ask_price_.Add(value);
}
inline void TickDataMes::add_ask_price(double value) {
  _internal_add_ask_price(value);
  // @@protoc_insertion_point(field_add:TickDataMes.ask_price)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TickDataMes::_internal_ask_price() const {
  return _impl_.ask_price_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TickDataMes::ask_price() const {
  // @@protoc_insertion_point(field_list:TickDataMes.ask_price)
  return _internal_ask_price();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TickDataMes::_internal_mutable_ask_price() {
  return &_impl_.ask_price_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TickDataMes::mutable_ask_price() {
  // @@protoc_insertion_point(field_mutable_list:TickDataMes.ask_price)
  return _internal_mutable_ask_price();
}

// double limit_up = 4;
inline void TickDataMes::clear_limit_up() {
  _impl_.limit_up_ = 0;
}
inline double TickDataMes::_internal_limit_up() const {
  return _impl_.limit_up_;
}
inline double TickDataMes::limit_up() const {
  // @@protoc_insertion_point(field_get:TickDataMes.limit_up)
  return _internal_limit_up();
}
inline void TickDataMes::_internal_set_limit_up(double value) {
  
  _impl_.limit_up_ = value;
}
inline void TickDataMes::set_limit_up(double value) {
  _internal_set_limit_up(value);
  // @@protoc_insertion_point(field_set:TickDataMes.limit_up)
}

// double limit_down = 5;
inline void TickDataMes::clear_limit_down() {
  _impl_.limit_down_ = 0;
}
inline double TickDataMes::_internal_limit_down() const {
  return _impl_.limit_down_;
}
inline double TickDataMes::limit_down() const {
  // @@protoc_insertion_point(field_get:TickDataMes.limit_down)
  return _internal_limit_down();
}
inline void TickDataMes::_internal_set_limit_down(double value) {
  
  _impl_.limit_down_ = value;
}
inline void TickDataMes::set_limit_down(double value) {
  _internal_set_limit_down(value);
  // @@protoc_insertion_point(field_set:TickDataMes.limit_down)
}

// int32 volume = 6;
inline void TickDataMes::clear_volume() {
  _impl_.volume_ = 0;
}
inline int32_t TickDataMes::_internal_volume() const {
  return _impl_.volume_;
}
inline int32_t TickDataMes::volume() const {
  // @@protoc_insertion_point(field_get:TickDataMes.volume)
  return _internal_volume();
}
inline void TickDataMes::_internal_set_volume(int32_t value) {
  
  _impl_.volume_ = value;
}
inline void TickDataMes::set_volume(int32_t value) {
  _internal_set_volume(value);
  // @@protoc_insertion_point(field_set:TickDataMes.volume)
}

// int32 updatemill = 7;
inline void TickDataMes::clear_updatemill() {
  _impl_.updatemill_ = 0;
}
inline int32_t TickDataMes::_internal_updatemill() const {
  return _impl_.updatemill_;
}
inline int32_t TickDataMes::updatemill() const {
  // @@protoc_insertion_point(field_get:TickDataMes.updatemill)
  return _internal_updatemill();
}
inline void TickDataMes::_internal_set_updatemill(int32_t value) {
  
  _impl_.updatemill_ = value;
}
inline void TickDataMes::set_updatemill(int32_t value) {
  _internal_set_updatemill(value);
  // @@protoc_insertion_point(field_set:TickDataMes.updatemill)
}

// repeated int32 bid_volume = 8;
inline int TickDataMes::_internal_bid_volume_size() const {
  return _impl_.bid_volume_.size();
}
inline int TickDataMes::bid_volume_size() const {
  return _internal_bid_volume_size();
}
inline void TickDataMes::clear_bid_volume() {
  _impl_.bid_volume_.Clear();
}
inline int32_t TickDataMes::_internal_bid_volume(int index) const {
  return _impl_.bid_volume_.Get(index);
}
inline int32_t TickDataMes::bid_volume(int index) const {
  // @@protoc_insertion_point(field_get:TickDataMes.bid_volume)
  return _internal_bid_volume(index);
}
inline void TickDataMes::set_bid_volume(int index, int32_t value) {
  _impl_.bid_volume_.Set(index, value);
  // @@protoc_insertion_point(field_set:TickDataMes.bid_volume)
}
inline void TickDataMes::_internal_add_bid_volume(int32_t value) {
  _impl_.bid_volume_.Add(value);
}
inline void TickDataMes::add_bid_volume(int32_t value) {
  _internal_add_bid_volume(value);
  // @@protoc_insertion_point(field_add:TickDataMes.bid_volume)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TickDataMes::_internal_bid_volume() const {
  return _impl_.bid_volume_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TickDataMes::bid_volume() const {
  // @@protoc_insertion_point(field_list:TickDataMes.bid_volume)
  return _internal_bid_volume();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TickDataMes::_internal_mutable_bid_volume() {
  return &_impl_.bid_volume_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TickDataMes::mutable_bid_volume() {
  // @@protoc_insertion_point(field_mutable_list:TickDataMes.bid_volume)
  return _internal_mutable_bid_volume();
}

// repeated int32 ask_volume = 9;
inline int TickDataMes::_internal_ask_volume_size() const {
  return _impl_.ask_volume_.size();
}
inline int TickDataMes::ask_volume_size() const {
  return _internal_ask_volume_size();
}
inline void TickDataMes::clear_ask_volume() {
  _impl_.ask_volume_.Clear();
}
inline int32_t TickDataMes::_internal_ask_volume(int index) const {
  return _impl_.ask_volume_.Get(index);
}
inline int32_t TickDataMes::ask_volume(int index) const {
  // @@protoc_insertion_point(field_get:TickDataMes.ask_volume)
  return _internal_ask_volume(index);
}
inline void TickDataMes::set_ask_volume(int index, int32_t value) {
  _impl_.ask_volume_.Set(index, value);
  // @@protoc_insertion_point(field_set:TickDataMes.ask_volume)
}
inline void TickDataMes::_internal_add_ask_volume(int32_t value) {
  _impl_.ask_volume_.Add(value);
}
inline void TickDataMes::add_ask_volume(int32_t value) {
  _internal_add_ask_volume(value);
  // @@protoc_insertion_point(field_add:TickDataMes.ask_volume)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TickDataMes::_internal_ask_volume() const {
  return _impl_.ask_volume_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TickDataMes::ask_volume() const {
  // @@protoc_insertion_point(field_list:TickDataMes.ask_volume)
  return _internal_ask_volume();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TickDataMes::_internal_mutable_ask_volume() {
  return &_impl_.ask_volume_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TickDataMes::mutable_ask_volume() {
  // @@protoc_insertion_point(field_mutable_list:TickDataMes.ask_volume)
  return _internal_mutable_ask_volume();
}

// int64 local_receive_time = 10;
inline void TickDataMes::clear_local_receive_time() {
  _impl_.local_receive_time_ = int64_t{0};
}
inline int64_t TickDataMes::_internal_local_receive_time() const {
  return _impl_.local_receive_time_;
}
inline int64_t TickDataMes::local_receive_time() const {
  // @@protoc_insertion_point(field_get:TickDataMes.local_receive_time)
  return _internal_local_receive_time();
}
inline void TickDataMes::_internal_set_local_receive_time(int64_t value) {
  
  _impl_.local_receive_time_ = value;
}
inline void TickDataMes::set_local_receive_time(int64_t value) {
  _internal_set_local_receive_time(value);
  // @@protoc_insertion_point(field_set:TickDataMes.local_receive_time)
}

// string InstrumentID = 11;
inline void TickDataMes::clear_instrumentid() {
  _impl_.instrumentid_.ClearToEmpty();
}
inline const std::string& TickDataMes::instrumentid() const {
  // @@protoc_insertion_point(field_get:TickDataMes.InstrumentID)
  return _internal_instrumentid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickDataMes::set_instrumentid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.instrumentid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TickDataMes.InstrumentID)
}
inline std::string* TickDataMes::mutable_instrumentid() {
  std::string* _s = _internal_mutable_instrumentid();
  // @@protoc_insertion_point(field_mutable:TickDataMes.InstrumentID)
  return _s;
}
inline const std::string& TickDataMes::_internal_instrumentid() const {
  return _impl_.instrumentid_.Get();
}
inline void TickDataMes::_internal_set_instrumentid(const std::string& value) {
  
  _impl_.instrumentid_.Set(value, GetArenaForAllocation());
}
inline std::string* TickDataMes::_internal_mutable_instrumentid() {
  
  return _impl_.instrumentid_.Mutable(GetArenaForAllocation());
}
inline std::string* TickDataMes::release_instrumentid() {
  // @@protoc_insertion_point(field_release:TickDataMes.InstrumentID)
  return _impl_.instrumentid_.Release();
}
inline void TickDataMes::set_allocated_instrumentid(std::string* instrumentid) {
  if (instrumentid != nullptr) {
    
  } else {
    
  }
  _impl_.instrumentid_.SetAllocated(instrumentid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instrumentid_.IsDefault()) {
    _impl_.instrumentid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TickDataMes.InstrumentID)
}

// string ExchangeID = 12;
inline void TickDataMes::clear_exchangeid() {
  _impl_.exchangeid_.ClearToEmpty();
}
inline const std::string& TickDataMes::exchangeid() const {
  // @@protoc_insertion_point(field_get:TickDataMes.ExchangeID)
  return _internal_exchangeid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickDataMes::set_exchangeid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.exchangeid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TickDataMes.ExchangeID)
}
inline std::string* TickDataMes::mutable_exchangeid() {
  std::string* _s = _internal_mutable_exchangeid();
  // @@protoc_insertion_point(field_mutable:TickDataMes.ExchangeID)
  return _s;
}
inline const std::string& TickDataMes::_internal_exchangeid() const {
  return _impl_.exchangeid_.Get();
}
inline void TickDataMes::_internal_set_exchangeid(const std::string& value) {
  
  _impl_.exchangeid_.Set(value, GetArenaForAllocation());
}
inline std::string* TickDataMes::_internal_mutable_exchangeid() {
  
  return _impl_.exchangeid_.Mutable(GetArenaForAllocation());
}
inline std::string* TickDataMes::release_exchangeid() {
  // @@protoc_insertion_point(field_release:TickDataMes.ExchangeID)
  return _impl_.exchangeid_.Release();
}
inline void TickDataMes::set_allocated_exchangeid(std::string* exchangeid) {
  if (exchangeid != nullptr) {
    
  } else {
    
  }
  _impl_.exchangeid_.SetAllocated(exchangeid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.exchangeid_.IsDefault()) {
    _impl_.exchangeid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TickDataMes.ExchangeID)
}

// string update_time = 13;
inline void TickDataMes::clear_update_time() {
  _impl_.update_time_.ClearToEmpty();
}
inline const std::string& TickDataMes::update_time() const {
  // @@protoc_insertion_point(field_get:TickDataMes.update_time)
  return _internal_update_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickDataMes::set_update_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.update_time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TickDataMes.update_time)
}
inline std::string* TickDataMes::mutable_update_time() {
  std::string* _s = _internal_mutable_update_time();
  // @@protoc_insertion_point(field_mutable:TickDataMes.update_time)
  return _s;
}
inline const std::string& TickDataMes::_internal_update_time() const {
  return _impl_.update_time_.Get();
}
inline void TickDataMes::_internal_set_update_time(const std::string& value) {
  
  _impl_.update_time_.Set(value, GetArenaForAllocation());
}
inline std::string* TickDataMes::_internal_mutable_update_time() {
  
  return _impl_.update_time_.Mutable(GetArenaForAllocation());
}
inline std::string* TickDataMes::release_update_time() {
  // @@protoc_insertion_point(field_release:TickDataMes.update_time)
  return _impl_.update_time_.Release();
}
inline void TickDataMes::set_allocated_update_time(std::string* update_time) {
  if (update_time != nullptr) {
    
  } else {
    
  }
  _impl_.update_time_.SetAllocated(update_time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.update_time_.IsDefault()) {
    _impl_.update_time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TickDataMes.update_time)
}

// string Action_Day = 14;
inline void TickDataMes::clear_action_day() {
  _impl_.action_day_.ClearToEmpty();
}
inline const std::string& TickDataMes::action_day() const {
  // @@protoc_insertion_point(field_get:TickDataMes.Action_Day)
  return _internal_action_day();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickDataMes::set_action_day(ArgT0&& arg0, ArgT... args) {
 
 _impl_.action_day_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TickDataMes.Action_Day)
}
inline std::string* TickDataMes::mutable_action_day() {
  std::string* _s = _internal_mutable_action_day();
  // @@protoc_insertion_point(field_mutable:TickDataMes.Action_Day)
  return _s;
}
inline const std::string& TickDataMes::_internal_action_day() const {
  return _impl_.action_day_.Get();
}
inline void TickDataMes::_internal_set_action_day(const std::string& value) {
  
  _impl_.action_day_.Set(value, GetArenaForAllocation());
}
inline std::string* TickDataMes::_internal_mutable_action_day() {
  
  return _impl_.action_day_.Mutable(GetArenaForAllocation());
}
inline std::string* TickDataMes::release_action_day() {
  // @@protoc_insertion_point(field_release:TickDataMes.Action_Day)
  return _impl_.action_day_.Release();
}
inline void TickDataMes::set_allocated_action_day(std::string* action_day) {
  if (action_day != nullptr) {
    
  } else {
    
  }
  _impl_.action_day_.SetAllocated(action_day, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.action_day_.IsDefault()) {
    _impl_.action_day_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TickDataMes.Action_Day)
}

// string TradingDay = 15;
inline void TickDataMes::clear_tradingday() {
  _impl_.tradingday_.ClearToEmpty();
}
inline const std::string& TickDataMes::tradingday() const {
  // @@protoc_insertion_point(field_get:TickDataMes.TradingDay)
  return _internal_tradingday();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TickDataMes::set_tradingday(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tradingday_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TickDataMes.TradingDay)
}
inline std::string* TickDataMes::mutable_tradingday() {
  std::string* _s = _internal_mutable_tradingday();
  // @@protoc_insertion_point(field_mutable:TickDataMes.TradingDay)
  return _s;
}
inline const std::string& TickDataMes::_internal_tradingday() const {
  return _impl_.tradingday_.Get();
}
inline void TickDataMes::_internal_set_tradingday(const std::string& value) {
  
  _impl_.tradingday_.Set(value, GetArenaForAllocation());
}
inline std::string* TickDataMes::_internal_mutable_tradingday() {
  
  return _impl_.tradingday_.Mutable(GetArenaForAllocation());
}
inline std::string* TickDataMes::release_tradingday() {
  // @@protoc_insertion_point(field_release:TickDataMes.TradingDay)
  return _impl_.tradingday_.Release();
}
inline void TickDataMes::set_allocated_tradingday(std::string* tradingday) {
  if (tradingday != nullptr) {
    
  } else {
    
  }
  _impl_.tradingday_.SetAllocated(tradingday, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tradingday_.IsDefault()) {
    _impl_.tradingday_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TickDataMes.TradingDay)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tick_5fdata_2eproto
