// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tick_data.proto

#include "tick_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR TickDataMes::TickDataMes(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bid_price_)*/{}
  , /*decltype(_impl_.ask_price_)*/{}
  , /*decltype(_impl_.bid_volume_)*/{}
  , /*decltype(_impl_._bid_volume_cached_byte_size_)*/{0}
  , /*decltype(_impl_.ask_volume_)*/{}
  , /*decltype(_impl_._ask_volume_cached_byte_size_)*/{0}
  , /*decltype(_impl_.instrumentid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.exchangeid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.update_time_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.action_day_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tradingday_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.last_price_)*/0
  , /*decltype(_impl_.limit_up_)*/0
  , /*decltype(_impl_.limit_down_)*/0
  , /*decltype(_impl_.volume_)*/0
  , /*decltype(_impl_.updatemill_)*/0
  , /*decltype(_impl_.local_receive_time_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TickDataMesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TickDataMesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TickDataMesDefaultTypeInternal() {}
  union {
    TickDataMes _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TickDataMesDefaultTypeInternal _TickDataMes_default_instance_;
static ::_pb::Metadata file_level_metadata_tick_5fdata_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_tick_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tick_5fdata_2eproto = nullptr;

const uint32_t TableStruct_tick_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.last_price_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.bid_price_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.ask_price_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.limit_up_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.limit_down_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.volume_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.updatemill_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.bid_volume_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.ask_volume_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.local_receive_time_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.instrumentid_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.exchangeid_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.update_time_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.action_day_),
  PROTOBUF_FIELD_OFFSET(::TickDataMes, _impl_.tradingday_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::TickDataMes)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_TickDataMes_default_instance_._instance,
};

const char descriptor_table_protodef_tick_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017tick_data.proto\"\274\002\n\013TickDataMes\022\022\n\nlas"
  "t_price\030\001 \001(\001\022\021\n\tbid_price\030\002 \003(\001\022\021\n\task_"
  "price\030\003 \003(\001\022\020\n\010limit_up\030\004 \001(\001\022\022\n\nlimit_d"
  "own\030\005 \001(\001\022\016\n\006volume\030\006 \001(\005\022\022\n\nupdatemill\030"
  "\007 \001(\005\022\022\n\nbid_volume\030\010 \003(\005\022\022\n\nask_volume\030"
  "\t \003(\005\022\032\n\022local_receive_time\030\n \001(\003\022\024\n\014Ins"
  "trumentID\030\013 \001(\t\022\022\n\nExchangeID\030\014 \001(\t\022\023\n\013u"
  "pdate_time\030\r \001(\t\022\022\n\nAction_Day\030\016 \001(\t\022\022\n\n"
  "TradingDay\030\017 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_tick_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tick_5fdata_2eproto = {
    false, false, 344, descriptor_table_protodef_tick_5fdata_2eproto,
    "tick_data.proto",
    &descriptor_table_tick_5fdata_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_tick_5fdata_2eproto::offsets,
    file_level_metadata_tick_5fdata_2eproto, file_level_enum_descriptors_tick_5fdata_2eproto,
    file_level_service_descriptors_tick_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tick_5fdata_2eproto_getter() {
  return &descriptor_table_tick_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tick_5fdata_2eproto(&descriptor_table_tick_5fdata_2eproto);

// ===================================================================

class TickDataMes::_Internal {
 public:
};

TickDataMes::TickDataMes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TickDataMes)
}
TickDataMes::TickDataMes(const TickDataMes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TickDataMes* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bid_price_){from._impl_.bid_price_}
    , decltype(_impl_.ask_price_){from._impl_.ask_price_}
    , decltype(_impl_.bid_volume_){from._impl_.bid_volume_}
    , /*decltype(_impl_._bid_volume_cached_byte_size_)*/{0}
    , decltype(_impl_.ask_volume_){from._impl_.ask_volume_}
    , /*decltype(_impl_._ask_volume_cached_byte_size_)*/{0}
    , decltype(_impl_.instrumentid_){}
    , decltype(_impl_.exchangeid_){}
    , decltype(_impl_.update_time_){}
    , decltype(_impl_.action_day_){}
    , decltype(_impl_.tradingday_){}
    , decltype(_impl_.last_price_){}
    , decltype(_impl_.limit_up_){}
    , decltype(_impl_.limit_down_){}
    , decltype(_impl_.volume_){}
    , decltype(_impl_.updatemill_){}
    , decltype(_impl_.local_receive_time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instrumentid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrumentid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instrumentid().empty()) {
    _this->_impl_.instrumentid_.Set(from._internal_instrumentid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.exchangeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchangeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_exchangeid().empty()) {
    _this->_impl_.exchangeid_.Set(from._internal_exchangeid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.update_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.update_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_update_time().empty()) {
    _this->_impl_.update_time_.Set(from._internal_update_time(), 
      _this->GetArenaForAllocation());
  }
  _impl_.action_day_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.action_day_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_action_day().empty()) {
    _this->_impl_.action_day_.Set(from._internal_action_day(), 
      _this->GetArenaForAllocation());
  }
  _impl_.tradingday_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tradingday_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tradingday().empty()) {
    _this->_impl_.tradingday_.Set(from._internal_tradingday(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.last_price_, &from._impl_.last_price_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.local_receive_time_) -
    reinterpret_cast<char*>(&_impl_.last_price_)) + sizeof(_impl_.local_receive_time_));
  // @@protoc_insertion_point(copy_constructor:TickDataMes)
}

inline void TickDataMes::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bid_price_){arena}
    , decltype(_impl_.ask_price_){arena}
    , decltype(_impl_.bid_volume_){arena}
    , /*decltype(_impl_._bid_volume_cached_byte_size_)*/{0}
    , decltype(_impl_.ask_volume_){arena}
    , /*decltype(_impl_._ask_volume_cached_byte_size_)*/{0}
    , decltype(_impl_.instrumentid_){}
    , decltype(_impl_.exchangeid_){}
    , decltype(_impl_.update_time_){}
    , decltype(_impl_.action_day_){}
    , decltype(_impl_.tradingday_){}
    , decltype(_impl_.last_price_){0}
    , decltype(_impl_.limit_up_){0}
    , decltype(_impl_.limit_down_){0}
    , decltype(_impl_.volume_){0}
    , decltype(_impl_.updatemill_){0}
    , decltype(_impl_.local_receive_time_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.instrumentid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instrumentid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchangeid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.exchangeid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.update_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.update_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.action_day_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.action_day_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tradingday_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tradingday_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TickDataMes::~TickDataMes() {
  // @@protoc_insertion_point(destructor:TickDataMes)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TickDataMes::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bid_price_.~RepeatedField();
  _impl_.ask_price_.~RepeatedField();
  _impl_.bid_volume_.~RepeatedField();
  _impl_.ask_volume_.~RepeatedField();
  _impl_.instrumentid_.Destroy();
  _impl_.exchangeid_.Destroy();
  _impl_.update_time_.Destroy();
  _impl_.action_day_.Destroy();
  _impl_.tradingday_.Destroy();
}

void TickDataMes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TickDataMes::Clear() {
// @@protoc_insertion_point(message_clear_start:TickDataMes)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bid_price_.Clear();
  _impl_.ask_price_.Clear();
  _impl_.bid_volume_.Clear();
  _impl_.ask_volume_.Clear();
  _impl_.instrumentid_.ClearToEmpty();
  _impl_.exchangeid_.ClearToEmpty();
  _impl_.update_time_.ClearToEmpty();
  _impl_.action_day_.ClearToEmpty();
  _impl_.tradingday_.ClearToEmpty();
  ::memset(&_impl_.last_price_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.local_receive_time_) -
      reinterpret_cast<char*>(&_impl_.last_price_)) + sizeof(_impl_.local_receive_time_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TickDataMes::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double last_price = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.last_price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double bid_price = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_bid_price(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 17) {
          _internal_add_bid_price(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double ask_price = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_ask_price(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 25) {
          _internal_add_ask_price(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double limit_up = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.limit_up_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double limit_down = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.limit_down_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 volume = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.volume_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 updatemill = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.updatemill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 bid_volume = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_bid_volume(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 64) {
          _internal_add_bid_volume(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 ask_volume = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_ask_volume(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 72) {
          _internal_add_ask_volume(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 local_receive_time = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.local_receive_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string InstrumentID = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_instrumentid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TickDataMes.InstrumentID"));
        } else
          goto handle_unusual;
        continue;
      // string ExchangeID = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_exchangeid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TickDataMes.ExchangeID"));
        } else
          goto handle_unusual;
        continue;
      // string update_time = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_update_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TickDataMes.update_time"));
        } else
          goto handle_unusual;
        continue;
      // string Action_Day = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_action_day();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TickDataMes.Action_Day"));
        } else
          goto handle_unusual;
        continue;
      // string TradingDay = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_tradingday();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TickDataMes.TradingDay"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TickDataMes::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TickDataMes)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double last_price = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_price = this->_internal_last_price();
  uint64_t raw_last_price;
  memcpy(&raw_last_price, &tmp_last_price, sizeof(tmp_last_price));
  if (raw_last_price != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_last_price(), target);
  }

  // repeated double bid_price = 2;
  if (this->_internal_bid_price_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_bid_price(), target);
  }

  // repeated double ask_price = 3;
  if (this->_internal_ask_price_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_ask_price(), target);
  }

  // double limit_up = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_up = this->_internal_limit_up();
  uint64_t raw_limit_up;
  memcpy(&raw_limit_up, &tmp_limit_up, sizeof(tmp_limit_up));
  if (raw_limit_up != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_limit_up(), target);
  }

  // double limit_down = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_down = this->_internal_limit_down();
  uint64_t raw_limit_down;
  memcpy(&raw_limit_down, &tmp_limit_down, sizeof(tmp_limit_down));
  if (raw_limit_down != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_limit_down(), target);
  }

  // int32 volume = 6;
  if (this->_internal_volume() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_volume(), target);
  }

  // int32 updatemill = 7;
  if (this->_internal_updatemill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_updatemill(), target);
  }

  // repeated int32 bid_volume = 8;
  {
    int byte_size = _impl_._bid_volume_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          8, _internal_bid_volume(), byte_size, target);
    }
  }

  // repeated int32 ask_volume = 9;
  {
    int byte_size = _impl_._ask_volume_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          9, _internal_ask_volume(), byte_size, target);
    }
  }

  // int64 local_receive_time = 10;
  if (this->_internal_local_receive_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(10, this->_internal_local_receive_time(), target);
  }

  // string InstrumentID = 11;
  if (!this->_internal_instrumentid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instrumentid().data(), static_cast<int>(this->_internal_instrumentid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TickDataMes.InstrumentID");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_instrumentid(), target);
  }

  // string ExchangeID = 12;
  if (!this->_internal_exchangeid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_exchangeid().data(), static_cast<int>(this->_internal_exchangeid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TickDataMes.ExchangeID");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_exchangeid(), target);
  }

  // string update_time = 13;
  if (!this->_internal_update_time().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_update_time().data(), static_cast<int>(this->_internal_update_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TickDataMes.update_time");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_update_time(), target);
  }

  // string Action_Day = 14;
  if (!this->_internal_action_day().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_action_day().data(), static_cast<int>(this->_internal_action_day().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TickDataMes.Action_Day");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_action_day(), target);
  }

  // string TradingDay = 15;
  if (!this->_internal_tradingday().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tradingday().data(), static_cast<int>(this->_internal_tradingday().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TickDataMes.TradingDay");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_tradingday(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TickDataMes)
  return target;
}

size_t TickDataMes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TickDataMes)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double bid_price = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_bid_price_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double ask_price = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_ask_price_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated int32 bid_volume = 8;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.bid_volume_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._bid_volume_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 ask_volume = 9;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.ask_volume_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._ask_volume_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string InstrumentID = 11;
  if (!this->_internal_instrumentid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instrumentid());
  }

  // string ExchangeID = 12;
  if (!this->_internal_exchangeid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_exchangeid());
  }

  // string update_time = 13;
  if (!this->_internal_update_time().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_update_time());
  }

  // string Action_Day = 14;
  if (!this->_internal_action_day().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_action_day());
  }

  // string TradingDay = 15;
  if (!this->_internal_tradingday().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tradingday());
  }

  // double last_price = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_price = this->_internal_last_price();
  uint64_t raw_last_price;
  memcpy(&raw_last_price, &tmp_last_price, sizeof(tmp_last_price));
  if (raw_last_price != 0) {
    total_size += 1 + 8;
  }

  // double limit_up = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_up = this->_internal_limit_up();
  uint64_t raw_limit_up;
  memcpy(&raw_limit_up, &tmp_limit_up, sizeof(tmp_limit_up));
  if (raw_limit_up != 0) {
    total_size += 1 + 8;
  }

  // double limit_down = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_down = this->_internal_limit_down();
  uint64_t raw_limit_down;
  memcpy(&raw_limit_down, &tmp_limit_down, sizeof(tmp_limit_down));
  if (raw_limit_down != 0) {
    total_size += 1 + 8;
  }

  // int32 volume = 6;
  if (this->_internal_volume() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_volume());
  }

  // int32 updatemill = 7;
  if (this->_internal_updatemill() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_updatemill());
  }

  // int64 local_receive_time = 10;
  if (this->_internal_local_receive_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_local_receive_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TickDataMes::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TickDataMes::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TickDataMes::GetClassData() const { return &_class_data_; }


void TickDataMes::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TickDataMes*>(&to_msg);
  auto& from = static_cast<const TickDataMes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TickDataMes)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.bid_price_.MergeFrom(from._impl_.bid_price_);
  _this->_impl_.ask_price_.MergeFrom(from._impl_.ask_price_);
  _this->_impl_.bid_volume_.MergeFrom(from._impl_.bid_volume_);
  _this->_impl_.ask_volume_.MergeFrom(from._impl_.ask_volume_);
  if (!from._internal_instrumentid().empty()) {
    _this->_internal_set_instrumentid(from._internal_instrumentid());
  }
  if (!from._internal_exchangeid().empty()) {
    _this->_internal_set_exchangeid(from._internal_exchangeid());
  }
  if (!from._internal_update_time().empty()) {
    _this->_internal_set_update_time(from._internal_update_time());
  }
  if (!from._internal_action_day().empty()) {
    _this->_internal_set_action_day(from._internal_action_day());
  }
  if (!from._internal_tradingday().empty()) {
    _this->_internal_set_tradingday(from._internal_tradingday());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_price = from._internal_last_price();
  uint64_t raw_last_price;
  memcpy(&raw_last_price, &tmp_last_price, sizeof(tmp_last_price));
  if (raw_last_price != 0) {
    _this->_internal_set_last_price(from._internal_last_price());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_up = from._internal_limit_up();
  uint64_t raw_limit_up;
  memcpy(&raw_limit_up, &tmp_limit_up, sizeof(tmp_limit_up));
  if (raw_limit_up != 0) {
    _this->_internal_set_limit_up(from._internal_limit_up());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_limit_down = from._internal_limit_down();
  uint64_t raw_limit_down;
  memcpy(&raw_limit_down, &tmp_limit_down, sizeof(tmp_limit_down));
  if (raw_limit_down != 0) {
    _this->_internal_set_limit_down(from._internal_limit_down());
  }
  if (from._internal_volume() != 0) {
    _this->_internal_set_volume(from._internal_volume());
  }
  if (from._internal_updatemill() != 0) {
    _this->_internal_set_updatemill(from._internal_updatemill());
  }
  if (from._internal_local_receive_time() != 0) {
    _this->_internal_set_local_receive_time(from._internal_local_receive_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TickDataMes::CopyFrom(const TickDataMes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TickDataMes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TickDataMes::IsInitialized() const {
  return true;
}

void TickDataMes::InternalSwap(TickDataMes* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bid_price_.InternalSwap(&other->_impl_.bid_price_);
  _impl_.ask_price_.InternalSwap(&other->_impl_.ask_price_);
  _impl_.bid_volume_.InternalSwap(&other->_impl_.bid_volume_);
  _impl_.ask_volume_.InternalSwap(&other->_impl_.ask_volume_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instrumentid_, lhs_arena,
      &other->_impl_.instrumentid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.exchangeid_, lhs_arena,
      &other->_impl_.exchangeid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.update_time_, lhs_arena,
      &other->_impl_.update_time_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.action_day_, lhs_arena,
      &other->_impl_.action_day_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.tradingday_, lhs_arena,
      &other->_impl_.tradingday_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TickDataMes, _impl_.local_receive_time_)
      + sizeof(TickDataMes::_impl_.local_receive_time_)
      - PROTOBUF_FIELD_OFFSET(TickDataMes, _impl_.last_price_)>(
          reinterpret_cast<char*>(&_impl_.last_price_),
          reinterpret_cast<char*>(&other->_impl_.last_price_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TickDataMes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tick_5fdata_2eproto_getter, &descriptor_table_tick_5fdata_2eproto_once,
      file_level_metadata_tick_5fdata_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TickDataMes*
Arena::CreateMaybeMessage< ::TickDataMes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TickDataMes >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
